### ISSUE TITLE
python 3.7 breaks aurman

### ISSUE THREAD

**Issue by polygamma** [polygamma/aurman#239]
It actually does not, just rebuild and reinstall `aurman`.

**Comment by polygamma** [comment]
I pushed a new version to the AUR, if users update `aurman` and `python` during the same execution of `aurman`, the problem does not arise.

**Comment by 0xE02B7** [comment]
Still getting error:

aurman
Traceback (most recent call last):
  File "/usr/bin/aurman", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aurman==2.16.10' distribution was not found and is required by the application

sudo pacman -Qs aurman
local/aurman 2.16.10-1
    aurman AUR helper with almost pacman syntax

python -V
Python 3.7.0

**Comment by polygamma** [comment]
deleted a comment which suggested installing aurman via the PKGBUILD found on Github, which is not the way to go.

**Comment by RBlaine95** [comment]
Apologies for the previous comment, didn't know that wasn't the way to do it.

Perhaps, if instead of curling the Github `PKGBUILD`, a `wget` of the latest `.tar.gz` would be more acceptable?

```bash
cd ~/Downloads
wget https://github.com/polygamma/aurman/archive/2.17.1.tar.gz
tar -zxvf 2.17.1.tar.gz
cd aurman-2.17.1
makepkg -si

# If PGP key problems
gpg --recv-keys $key_id
```

**Comment by polygamma** [comment]
Sorry @RBlaine95, I don't like explicit solutions for such problems in GitHub issues. `aurman` is targeted at advanced users, if they do not know how to rebuild `aurman`, they should not use it.

**Comment by eli-schwartz** [comment]
Okay, this is not rocket science, people.

Python received a major update, you must rebuild *all* python packages, no exceptions, aurman is just one of those packages.

If you use the AUR, that's your responsibility. If you use Antergos, that is the responsibility of Antergos **and you should discuss this with the Antergos packagers not with the aurman developer**.

**Comment by Babu87811** [comment]
in my case rebuilding aurman does not help at all. I am on arch:

```
==> Retrieving sources...
  -> Cloning xfce4-pulseaudio-plugin git repo...
Cloning into bare repository '/home/bednar/.cache/aurman/xfce4-pulseaudio-plugin-git/xfce4-pulseaudio-plugin'...
fatal: unable to connect to git.xfce.org:
git.xfce.org[0: 138.48.2.107]: errno=Connection timed out

==> ERROR: Failure while downloading xfce4-pulseaudio-plugin git repo
    Aborting...
2018-08-08 21:45:22,472 - wrappers - makepkg - ERROR - makepkg query ['makepkg', '-odc', '--noprepare', '--skipinteg'] failed in directory /home/bednar/.cache/aurman/xfce4-pulseaudio-plugin-git
2018-08-08 21:45:22,472 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/aurman/main.py", line 1245, in main
    process(argv[1:])
  File "/usr/lib/python3.7/site-packages/aurman/main.py", line 965, in process
    package.get_devel_version(ignore_arch)
  File "/usr/lib/python3.7/site-packages/aurman/classes.py", line 1179, in get_devel_version
    makepkg(["-odc", "--noprepare", "--skipinteg"], False, package_dir)
  File "/usr/lib/python3.7/site-packages/aurman/wrappers.py", line 137, in makepkg
    raise InvalidInput("makepkg query {} failed in directory {}".format(makepkg_query, dir_to_execute))
aurman.own_exceptions.InvalidInput: makepkg query ['makepkg', '-odc', '--noprepare', '--skipinteg'] failed in directory /home/bednar/.cache/aurman/xfce4-pulseaudio-plugin-git
aurman -Syu --devel  37.33s user 8.84s system 21% cpu 3:34.00 total
```

**Comment by eli-schwartz** [comment]
Did you actually read that error message at all??? It is telling you that makepkg failed to run with the error message:

```
fatal: unable to connect to git.xfce.org:
git.xfce.org[0: 138.48.2.107]: errno=Connection timed out
```

What on earth possessed you to think this had anything to do with python 3.7?

**Comment by Babu87811** [comment]
```
 File "/usr/lib/python3.7/site-packages/aurman/main.py", line 1245, in main
    process(argv[1:])
  File "/usr/lib**/python3.7**/site-packages/aurman/main.py", line 965, in process
    package.get_devel_version(ignore_arch)
  File "/usr/lib/**python3.7**/site-packages/aurman/classes.py", line 1179, in get_devel_version
    makepkg(["-odc", "--noprepare", "--skipinteg"], False, package_dir)
  File "/usr/lib/**python3.7**/site-packages/aurman/wrappers.py", line 137, in makepkg
    raise InvalidInput("makepkg query {} failed in directory {}".format(makepkg_query, dir_to_execute))
aurman.own_exceptions.InvalidInput: makepkg query ['makepkg', '-odc', '--noprepare', '--skipinteg'] failed in directory /home/bednar/.cache/aurman/xfce4-pulseaudio-plugin-git
```

Thanks, smartass.

**Comment by polygamma** [comment]
@Babu87811 has been banned
