### ISSUE TITLE
aurman can accidentally be installed in a venv

### ISSUE THREAD

**Issue by hawkowl** [polygamma/aurman#53]
`python` on my system goes to a "local commands" virtual environment, which is Python 2.7, not the global Python 3 that aurman wants. I fixed it with this patch (which is the recommended way of getting the correct Python) but I'm not sure about any Arch-specific standards.

```
diff --git a/PKGBUILD b/PKGBUILD
index 2ac7e58..5cf95d3 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -12,6 +12,6 @@ md5sums=('SKIP')
 
 package() {
     cd "$srcdir/aurman_sources"
-    python setup.py install --root="$pkgdir/" --optimize=1
+    /usr/bin/env python3 setup.py install --root="$pkgdir/" --optimize=1
     install -Dm644 ./bash.completion "$pkgdir/usr/share/bash-completion/completions/aurman"
 }
```

**Comment by polygamma** [comment]
Done. see: https://github.com/polygamma/aurman/commit/f5cf6a2494fabee909b5802f2effd3151cc038c0

**Comment by grst** [comment]
Actually, using `env` does not solve the problem. 
The package command should refer to `/usr/bin/python` which is the python that is installed by pacman as a dependency. 

**Background:**
I use Anaconda python as the default python in my `PATH`. Using `env`, the Anaconda-python is used when I install aurman. This results in the error message that the `pycman` package cannot be found. 
When I manually edit the `PKGBUILD` to use `/usr/bin/python` everything works as expected.

**Comment by polygamma** [comment]
Will change it to `/usr/bin/python3`

**Comment by polygamma** [comment]
done. see: https://github.com/polygamma/aurman/commit/82285b7c274d0b1f5ec69248d8328fedc3b6afc2

this fixes the problem, i guess?

**Comment by grst** [comment]
yes, thanks!

**Comment by polygamma** [comment]
great :)
